# Generated by Django 2.0.3 on 2018-03-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='data',
            new_name='date',
        ),
    ]
